
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace real_estate_agency.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Ad
{

    public int Id { get; set; }

    public string Title { get; set; }

    public string Type { get; set; }

    public string Address { get; set; }

    public string Area { get; set; }

    public Nullable<double> Latitude { get; set; }

    public Nullable<double> Longitude { get; set; }

    public string Author { get; set; }

    public string Images { get; set; }

    public string Phone { get; set; }

    public string Value { get; set; }

    public string Details { get; set; }

    public string Floors { get; set; }

    public string FloorsCount { get; set; }

    public string RoomsCount { get; set; }

    public string PrevImage { get; set; }

    public string AdUrl { get; set; }

}

}
