

//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace real_estate_agency.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class RealEstateDBEntities : DbContext
{
    public RealEstateDBEntities()
        : base("name=RealEstateDBEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Ad> Ads { get; set; }

}

}

