//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace real_estate_agency.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("real_estate_agency.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверное имя или пароль!.
        /// </summary>
        public static string AccountValidator1 {
            get {
                return ResourceManager.GetString("AccountValidator1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Активируйте свою учетную запись. Проверьте почту!.
        /// </summary>
        public static string AccountValidator2 {
            get {
                return ResourceManager.GetString("AccountValidator2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ваша учетная запись заблокирована до .
        /// </summary>
        public static string AccountValidator3 {
            get {
                return ResourceManager.GetString("AccountValidator3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Превышено количество попыток входа..
        /// </summary>
        public static string AccountValidator4 {
            get {
                return ResourceManager.GetString("AccountValidator4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Возможно, кто-то пытается взломать Вашу учетную запись.
        /// </summary>
        public static string AccountValidator5 {
            get {
                return ResourceManager.GetString("AccountValidator5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверный пароль! Осталось попыток: .
        /// </summary>
        public static string AccountValidator6 {
            get {
                return ResourceManager.GetString("AccountValidator6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Укажите Email!.
        /// </summary>
        public static string AccountValidator7 {
            get {
                return ResourceManager.GetString("AccountValidator7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пользователя с таким Email не существует!.
        /// </summary>
        public static string AccountValidator8 {
            get {
                return ResourceManager.GetString("AccountValidator8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Новый пароль успешно установлен!.
        /// </summary>
        public static string AccountValidator9 {
            get {
                return ResourceManager.GetString("AccountValidator9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить объявление.
        /// </summary>
        public static string AddAd {
            get {
                return ResourceManager.GetString("AddAd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить.
        /// </summary>
        public static string AddButton {
            get {
                return ResourceManager.GetString("AddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Адрес.
        /// </summary>
        public static string AddEditAddress {
            get {
                return ResourceManager.GetString("AddEditAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Площадь.
        /// </summary>
        public static string AddEditArea {
            get {
                return ResourceManager.GetString("AddEditArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Автор.
        /// </summary>
        public static string AddEditAuthor {
            get {
                return ResourceManager.GetString("AddEditAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Категория.
        /// </summary>
        public static string AddEditCategory {
            get {
                return ResourceManager.GetString("AddEditCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Описание.
        /// </summary>
        public static string AddEditDetails {
            get {
                return ResourceManager.GetString("AddEditDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Этаж.
        /// </summary>
        public static string AddEditFloor {
            get {
                return ResourceManager.GetString("AddEditFloor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Этажность.
        /// </summary>
        public static string AddEditFloorsCount {
            get {
                return ResourceManager.GetString("AddEditFloorsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на из.
        /// </summary>
        public static string AddEditFrom {
            get {
                return ResourceManager.GetString("AddEditFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заголовок.
        /// </summary>
        public static string AddEditHeader {
            get {
                return ResourceManager.GetString("AddEditHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изображение на превью.
        /// </summary>
        public static string AddEditImageOnPreview {
            get {
                return ResourceManager.GetString("AddEditImageOnPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на перейти.
        /// </summary>
        public static string AddEditLink {
            get {
                return ResourceManager.GetString("AddEditLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Оригинал.
        /// </summary>
        public static string AddEditOrigin {
            get {
                return ResourceManager.GetString("AddEditOrigin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Телефон(ы).
        /// </summary>
        public static string AddEditPhones {
            get {
                return ResourceManager.GetString("AddEditPhones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фотографии.
        /// </summary>
        public static string AddEditPhotos {
            get {
                return ResourceManager.GetString("AddEditPhotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Цена.
        /// </summary>
        public static string AddEditQuantity {
            get {
                return ResourceManager.GetString("AddEditQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить объявление!.
        /// </summary>
        public static string AddEditRemoveAd {
            get {
                return ResourceManager.GetString("AddEditRemoveAd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Комнаты.
        /// </summary>
        public static string AddEditRoomsCount {
            get {
                return ResourceManager.GetString("AddEditRoomsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тип.
        /// </summary>
        public static string AddEditType {
            get {
                return ResourceManager.GetString("AddEditType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить модератора.
        /// </summary>
        public static string AddModerator {
            get {
                return ResourceManager.GetString("AddModerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить новое объявление.
        /// </summary>
        public static string AddNewAd {
            get {
                return ResourceManager.GetString("AddNewAd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить подписку.
        /// </summary>
        public static string AddPremium {
            get {
                return ResourceManager.GetString("AddPremium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить цену.
        /// </summary>
        public static string AddQuantity {
            get {
                return ResourceManager.GetString("AddQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Административная панель.
        /// </summary>
        public static string AdminPanel {
            get {
                return ResourceManager.GetString("AdminPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Модератора с таким id не существует!.
        /// </summary>
        public static string AdminValidator1 {
            get {
                return ResourceManager.GetString("AdminValidator1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Все категории.
        /// </summary>
        public static string AllCategories {
            get {
                return ResourceManager.GetString("AllCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заблокировать.
        /// </summary>
        public static string Block {
            get {
                return ResourceManager.GetString("Block", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заблокирован.
        /// </summary>
        public static string Blocked {
            get {
                return ResourceManager.GetString("Blocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заблокировать пользователя.
        /// </summary>
        public static string BlockUser {
            get {
                return ResourceManager.GetString("BlockUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Приобрести премиум подписку.
        /// </summary>
        public static string BuyPremium {
            get {
                return ResourceManager.GetString("BuyPremium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сменить.
        /// </summary>
        public static string ChangeButton {
            get {
                return ResourceManager.GetString("ChangeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изменить пароль.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подтвердить.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подтвердите новый пароль.
        /// </summary>
        public static string ConfirmNewPassword {
            get {
                return ResourceManager.GetString("ConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подтвердите пароль.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Текущий пароль.
        /// </summary>
        public static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароль должен содержать не менее 6 символов!.
        /// </summary>
        public static string CustomPassValidator1 {
            get {
                return ResourceManager.GetString("CustomPassValidator1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароль должен содержать цифры и буквы латинского алфавита!.
        /// </summary>
        public static string CustomPassValidator2 {
            get {
                return ResourceManager.GetString("CustomPassValidator2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверный формат Email адреса!.
        /// </summary>
        public static string CustomUserValidator1 {
            get {
                return ResourceManager.GetString("CustomUserValidator1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Указанный Email уже используется другим пользоветелем!.
        /// </summary>
        public static string CustomUserValidator2 {
            get {
                return ResourceManager.GetString("CustomUserValidator2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пользователь с таким логином уже существует!.
        /// </summary>
        public static string CustomUserValidator3 {
            get {
                return ResourceManager.GetString("CustomUserValidator3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подробнее....
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отредактировать объявление.
        /// </summary>
        public static string EditAd {
            get {
                return ResourceManager.GetString("EditAd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на При обработке запроса произошла ошибка.
        /// </summary>
        public static string ErrorPageMessage {
            get {
                return ResourceManager.GetString("ErrorPageMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка!.
        /// </summary>
        public static string ErrorPageTitle {
            get {
                return ResourceManager.GetString("ErrorPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Этаж от.
        /// </summary>
        public static string FilterFloorFrom {
            get {
                return ResourceManager.GetString("FilterFloorFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Этаж до.
        /// </summary>
        public static string FilterFloorTo {
            get {
                return ResourceManager.GetString("FilterFloorTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Цена от.
        /// </summary>
        public static string FilterQuantityFrom {
            get {
                return ResourceManager.GetString("FilterQuantityFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Цена до.
        /// </summary>
        public static string FilterQuantityTo {
            get {
                return ResourceManager.GetString("FilterQuantityTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Комнат от.
        /// </summary>
        public static string FilterRoomsFrom {
            get {
                return ResourceManager.GetString("FilterRoomsFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Комнат до.
        /// </summary>
        public static string FilterRoomsTo {
            get {
                return ResourceManager.GetString("FilterRoomsTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поиск.
        /// </summary>
        public static string Find {
            get {
                return ResourceManager.GetString("Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Найти!.
        /// </summary>
        public static string FindAd {
            get {
                return ResourceManager.GetString("FindAd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на От.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Получить последние объявления.
        /// </summary>
        public static string GetLastAds {
            get {
                return ResourceManager.GetString("GetLastAds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите причину блокировки.
        /// </summary>
        public static string InputBlockReason {
            get {
                return ResourceManager.GetString("InputBlockReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите email.
        /// </summary>
        public static string InputEmail {
            get {
                return ResourceManager.GetString("InputEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите логин.
        /// </summary>
        public static string InputLogin {
            get {
                return ResourceManager.GetString("InputLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите логин или email.
        /// </summary>
        public static string InputLoginOrEmail {
            get {
                return ResourceManager.GetString("InputLoginOrEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите имя.
        /// </summary>
        public static string InputName {
            get {
                return ResourceManager.GetString("InputName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите пароль.
        /// </summary>
        public static string InputPassword {
            get {
                return ResourceManager.GetString("InputPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Язык.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Войти.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Логин.
        /// </summary>
        public static string LoginName {
            get {
                return ResourceManager.GetString("LoginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выйти.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подтвердите новый пароль!.
        /// </summary>
        public static string ModelValidatorConfirmNewPassword {
            get {
                return ResourceManager.GetString("ModelValidatorConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на День.
        /// </summary>
        public static string ModelValidatorInpitBlockDay {
            get {
                return ResourceManager.GetString("ModelValidatorInpitBlockDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Час.
        /// </summary>
        public static string ModelValidatorInpitBlockHour {
            get {
                return ResourceManager.GetString("ModelValidatorInpitBlockHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Месяц.
        /// </summary>
        public static string ModelValidatorInpitBlockMonth {
            get {
                return ResourceManager.GetString("ModelValidatorInpitBlockMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Навсегда.
        /// </summary>
        public static string ModelValidatorInpitBlockPermanently {
            get {
                return ResourceManager.GetString("ModelValidatorInpitBlockPermanently", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неделя.
        /// </summary>
        public static string ModelValidatorInpitBlockWeek {
            get {
                return ResourceManager.GetString("ModelValidatorInpitBlockWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подтвердите пароль!.
        /// </summary>
        public static string ModelValidatorInputConfirmationPassword {
            get {
                return ResourceManager.GetString("ModelValidatorInputConfirmationPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите текущий пароль!.
        /// </summary>
        public static string ModelValidatorInputCurrentPassword {
            get {
                return ResourceManager.GetString("ModelValidatorInputCurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Укажите длительность!.
        /// </summary>
        public static string ModelValidatorInputDurability {
            get {
                return ResourceManager.GetString("ModelValidatorInputDurability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите Email!.
        /// </summary>
        public static string ModelValidatorInputEmail {
            get {
                return ResourceManager.GetString("ModelValidatorInputEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите логин!.
        /// </summary>
        public static string ModelValidatorInputLogin {
            get {
                return ResourceManager.GetString("ModelValidatorInputLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите логин или Email!.
        /// </summary>
        public static string ModelValidatorInputLoginOrEmail {
            get {
                return ResourceManager.GetString("ModelValidatorInputLoginOrEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите имя!.
        /// </summary>
        public static string ModelValidatorInputName {
            get {
                return ResourceManager.GetString("ModelValidatorInputName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите новый пароль!.
        /// </summary>
        public static string ModelValidatorInputNewPassword {
            get {
                return ResourceManager.GetString("ModelValidatorInputNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите пароль!.
        /// </summary>
        public static string ModelValidatorInputPassword {
            get {
                return ResourceManager.GetString("ModelValidatorInputPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Укажите причину!.
        /// </summary>
        public static string ModelValidatorInputReason {
            get {
                return ResourceManager.GetString("ModelValidatorInputReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Длина имени должна быть от 3 до 50 символов!.
        /// </summary>
        public static string ModelValidatorLenName {
            get {
                return ResourceManager.GetString("ModelValidatorLenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Панель модератора.
        /// </summary>
        public static string ModeratorPanel {
            get {
                return ResourceManager.GetString("ModeratorPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Модераторы.
        /// </summary>
        public static string Moderators {
            get {
                return ResourceManager.GetString("Moderators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Такого пользователя не существует!.
        /// </summary>
        public static string ModeratorValidator1 {
            get {
                return ResourceManager.GetString("ModeratorValidator1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Мои объявления.
        /// </summary>
        public static string MyAds {
            get {
                return ResourceManager.GetString("MyAds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Мои закладки.
        /// </summary>
        public static string MyBookmarks {
            get {
                return ResourceManager.GetString("MyBookmarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Мои платежи.
        /// </summary>
        public static string MyPayments {
            get {
                return ResourceManager.GetString("MyPayments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Новый пароль.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на У вас еще нет объявлений.
        /// </summary>
        public static string NoAds {
            get {
                return ResourceManager.GetString("NoAds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на У вас еще нет закладок.
        /// </summary>
        public static string NoBookmarks {
            get {
                return ResourceManager.GetString("NoBookmarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Оповещений нет!.
        /// </summary>
        public static string NoNotifications {
            get {
                return ResourceManager.GetString("NoNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на У вас нет платежей.
        /// </summary>
        public static string NoPayments {
            get {
                return ResourceManager.GetString("NoPayments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Оповещения.
        /// </summary>
        public static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Восстановление пароля.
        /// </summary>
        public static string PasswordRecovery {
            get {
                return ResourceManager.GetString("PasswordRecovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на На указанный адрес будет отправлено сообщение со специальной ссылкой, с помощью которой вы сможете восстановить пароль..
        /// </summary>
        public static string PasswordRecoveryMessage {
            get {
                return ResourceManager.GetString("PasswordRecoveryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введенные пароли не совпадают!.
        /// </summary>
        public static string PasswordValidator1 {
            get {
                return ResourceManager.GetString("PasswordValidator1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Новые пароли не совпадают, подтвердите еще раз!.
        /// </summary>
        public static string PasswordValidator2 {
            get {
                return ResourceManager.GetString("PasswordValidator2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверный текущий пароль!.
        /// </summary>
        public static string PasswordValidator3 {
            get {
                return ResourceManager.GetString("PasswordValidator3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Платеж подтвержден.
        /// </summary>
        public static string PaymentConfirmed {
            get {
                return ResourceManager.GetString("PaymentConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на К оплате.
        /// </summary>
        public static string PaymentForPay {
            get {
                return ResourceManager.GetString("PaymentForPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Платеж пока не подтвержден.
        /// </summary>
        public static string PaymentNotConfirmed {
            get {
                return ResourceManager.GetString("PaymentNotConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Номер квитанции.
        /// </summary>
        public static string PaymentNumber {
            get {
                return ResourceManager.GetString("PaymentNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Личный кабинет.
        /// </summary>
        public static string PersonalCabinet {
            get {
                return ResourceManager.GetString("PersonalCabinet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Премиум.
        /// </summary>
        public static string Premium {
            get {
                return ResourceManager.GetString("Premium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Купить.
        /// </summary>
        public static string PremiumBuyButton {
            get {
                return ResourceManager.GetString("PremiumBuyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Расценки подписок.
        /// </summary>
        public static string PremiumCostTable {
            get {
                return ResourceManager.GetString("PremiumCostTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Количество дней.
        /// </summary>
        public static string PremiumDaysCount {
            get {
                return ResourceManager.GetString("PremiumDaysCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Длительность.
        /// </summary>
        public static string PremiumDuration {
            get {
                return ResourceManager.GetString("PremiumDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на дней.
        /// </summary>
        public static string PremiumOnDays {
            get {
                return ResourceManager.GetString("PremiumOnDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Цена.
        /// </summary>
        public static string PremiumQuantity {
            get {
                return ResourceManager.GetString("PremiumQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сумма.
        /// </summary>
        public static string PremiumSum {
            get {
                return ResourceManager.GetString("PremiumSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на У вас уже есть активная премиум подписка!.
        /// </summary>
        public static string PremiumWarning {
            get {
                return ResourceManager.GetString("PremiumWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на После подтверждения вы будете перенаправлены на страницу оплаты LiqPay.
        /// </summary>
        public static string PremiumWarning2 {
            get {
                return ResourceManager.GetString("PremiumWarning2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Профиль.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Настройки профиля.
        /// </summary>
        public static string ProfileSettings {
            get {
                return ResourceManager.GetString("ProfileSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Причина.
        /// </summary>
        public static string Reason {
            get {
                return ResourceManager.GetString("Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Зарегистрироваться.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Регистрация.
        /// </summary>
        public static string Registration {
            get {
                return ResourceManager.GetString("Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить объявление пользователя.
        /// </summary>
        public static string RemoveUserAd {
            get {
                return ResourceManager.GetString("RemoveUserAd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изменения успешно сохранены!.
        /// </summary>
        public static string SavingValidator1 {
            get {
                return ResourceManager.GetString("SavingValidator1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отправить.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не сортировать.
        /// </summary>
        public static string SortType1 {
            get {
                return ResourceManager.GetString("SortType1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на По возрастанию цены.
        /// </summary>
        public static string SortType2 {
            get {
                return ResourceManager.GetString("SortType2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на По убыванию цены.
        /// </summary>
        public static string SortType3 {
            get {
                return ResourceManager.GetString("SortType3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Длительность подписки (дни).
        /// </summary>
        public static string SubDuration {
            get {
                return ResourceManager.GetString("SubDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Разблокировать.
        /// </summary>
        public static string Unblock {
            get {
                return ResourceManager.GetString("Unblock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пользователи.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
    }
}
